language: java
jdk: openjdk8
sudo: true
dist: xenial

env:
  - TESTBENCH=-Dvaadin.proKey=$VAADIN_PRO_KEY_USER/$VAADIN_PRO_KEY_KEY
  - SAUCE_USER_EN=-Dsauce.user=$SAUCE_USER
  - SAUCE_ACCESS_KEY_EN=-sauce.sauceAccessKey=$SAUCE_ACCESS_KEY

before_install:
  - gem install rake


addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect:
    username: $SAUCE_USER
    access_key: $SAUCE_ACCESS_KEY


install: true
script: xvfb-run  --server-args="-screen 0 1024x768x24" mvn -B -e -V clean verify -Pit-saucelabs,production -Dvaadin.bowerMode=false $TESTBENCH $SAUSE_USER_EN $SAUCE_ACCESS_KEY_EN

