language: java
jdk: openjdk8
sudo: true
dist: xenial

env:
  - TESTBENCH=-Dvaadin.proKey=$VAADIN_PRO_KEY

before_install:
  - gem install rake


addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


install: true
script: xvfb-run  --server-args="-screen 0 1024x768x24" mvn -B -e -V clean verify -Pit,production -Dvaadin.bowerMode=false